In [1]:
from google.colab import files

uploaded = files.upload()

Saving dataset1.csv to dataset1.csv

In [3]:
import pandas as pd

diet_df = pd.read_csv("dataset1.csv")

diet_df.head()

,RecipeId,Name,CookTime,PrepTime,TotalTime,RecipeIngredientParts,Calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeInstructions
0,41,Carina's Tofu-Vegetable Kebabs,20,1440,1460,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...",536.1,24.0,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,"c(""Drain the tofu, carefully squeezing out exc..."
1,64,Almond Pound Cake,60,15,75,"c(""butter"", ""almond paste"", ""sugar"", ""eggs"", ""...",408.5,17.9,9.0,118.9,159.4,56.0,1.3,29.0,6.9,"c(""Preheat oven to 350 degrees Fahrenheit."", ""..."
2,94,Blueberry Buttertarts,25,15,40,"c(""egg"", ""corn syrup"", ""lemon juice"", ""vanilla...",337.9,18.4,4.7,17.6,125.7,40.2,1.2,11.5,4.2,"c(""Preheat oven to 375F."", ""Leave shells in fo..."
3,131,Buttermilk-Oat Bread,20,30,50,"c(""buttermilk"", ""honey"", ""butter"", ""margarine""...",68.7,0.7,0.3,1.4,88.4,13.3,0.6,1.7,2.1,"c(""For toasted rolled oats, place oats in a sh..."
4,168,Anzac Biscuits,15,10,25,"c(""rolled oats"", ""plain flour"", ""sugar"", ""gold...",199.4,10.4,6.8,22.3,143.4,25.0,1.5,10.9,2.2,"c(""Mix oats, flour, sugar and coconut together..."

In [4]:
print(diet_df.columns.tolist())

['RecipeId', 'Name', 'CookTime', 'PrepTime', 'TotalTime', 'RecipeIngredientParts', 'Calories', 'FatContent', 'SaturatedFatContent', 'CholesterolContent', 'SodiumContent', 'CarbohydrateContent', 'FiberContent', 'SugarContent', 'ProteinContent', 'RecipeInstructions']

In [5]:
diet_df = diet_df[
    [
        "Name",
        "Calories",
        "ProteinContent",
        "CarbohydrateContent",
        "FatContent",
        "FiberContent",
        "RecipeIngredientParts"
    ]
]

diet_df.head()

,Name,Calories,ProteinContent,CarbohydrateContent,FatContent,FiberContent,RecipeIngredientParts
0,Carina's Tofu-Vegetable Kebabs,536.1,29.3,64.2,24.0,17.3,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""..."
1,Almond Pound Cake,408.5,6.9,56.0,17.9,1.3,"c(""butter"", ""almond paste"", ""sugar"", ""eggs"", ""..."
2,Blueberry Buttertarts,337.9,4.2,40.2,18.4,1.2,"c(""egg"", ""corn syrup"", ""lemon juice"", ""vanilla..."
3,Buttermilk-Oat Bread,68.7,2.1,13.3,0.7,0.6,"c(""buttermilk"", ""honey"", ""butter"", ""margarine""..."
4,Anzac Biscuits,199.4,2.2,25.0,10.4,1.5,"c(""rolled oats"", ""plain flour"", ""sugar"", ""gold..."

In [6]:
diet_df = diet_df.dropna()

diet_df = diet_df.reset_index(drop=True)

print(diet_df.shape)

(22717, 7)

In [7]:
def assign_goal(calories):

    if calories <= 300:
        return "Weight Loss"

    elif calories <= 600:
        return "Maintain"

    else:
        return "Muscle Gain"


diet_df["Goal"] = diet_df["Calories"].apply(assign_goal)

In [8]:
def meal_type(calories):

    if calories < 250:
        return "Snack"

    elif calories < 450:
        return "Breakfast"

    elif calories < 700:
        return "Lunch"

    else:
        return "Dinner"


diet_df["Meal"] = diet_df["Calories"].apply(meal_type)

In [9]:
diet_df.head()

,Name,Calories,ProteinContent,CarbohydrateContent,FatContent,FiberContent,RecipeIngredientParts,Goal,Meal
0,Carina's Tofu-Vegetable Kebabs,536.1,29.3,64.2,24.0,17.3,"c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...",Maintain,Lunch
1,Almond Pound Cake,408.5,6.9,56.0,17.9,1.3,"c(""butter"", ""almond paste"", ""sugar"", ""eggs"", ""...",Maintain,Breakfast
2,Blueberry Buttertarts,337.9,4.2,40.2,18.4,1.2,"c(""egg"", ""corn syrup"", ""lemon juice"", ""vanilla...",Maintain,Breakfast
3,Buttermilk-Oat Bread,68.7,2.1,13.3,0.7,0.6,"c(""buttermilk"", ""honey"", ""butter"", ""margarine""...",Weight Loss,Snack
4,Anzac Biscuits,199.4,2.2,25.0,10.4,1.5,"c(""rolled oats"", ""plain flour"", ""sugar"", ""gold...",Weight Loss,Snack

In [10]:
import joblib

joblib.dump(diet_df, "diet_database.pkl")

['diet_database.pkl']

In [11]:
from google.colab import files

files.download("diet_database.pkl")